#Código y pruebas

In [ ]:
import numpy as np

def calcular_valores_vectores_propios(matriz):
    # Paso 1: Verificar si la matriz es cuadrada
    filas, columnas = matriz.shape
    if filas != columnas:
        raise ValueError("La matriz debe ser cuadrada.")

    # Paso 2: Calcular el polinomio característico
    I = np.eye(filas)  # Matriz identidad
    # Los valores propios son las raíces del determinante de (A - λI) = 0
    polinomio = np.poly(matriz)  # Polinomio característico

    # Paso 3: Calcular los valores propios resolviendo el polinomio característico
    valores_propios = np.roots(polinomio)

    # Paso 4: Calcular los vectores propios
    vectores_propios = []
    for lambda_val in valores_propios:
        # Resolver (A - λI) * v = 0
        A_lambda_I = matriz - lambda_val * I
        _, _, vh = np.linalg.svd(A_lambda_I)  # Descomposición SVD para resolver sistemas homogéneos
        vector_propio = vh[-1, :]  # El vector propio asociado
        vectores_propios.append(vector_propio)

    vectores_propios = np.array(vectores_propios).T  # Transponer para mantener formato convencional

    return valores_propios, vectores_propios


# Prueba de matriz A
matriz = np.array([[2, 1],
                   [3, 4]])

valores, vectores = calcular_valores_vectores_propios(matriz)

print("Valores propios:")
print(valores)

print("Vectores propios (columnas):")
print(vectores)


Valores propios:
[5. 1.]
Vectores propios (columnas):
[[-0.31622777 -0.70710678]
 [-0.9486833   0.70710678]]


In [ ]:
import numpy as np

def calcular_valores_vectores_propios(matriz):
    # Paso 1: Verificar si la matriz es cuadrada
    filas, columnas = matriz.shape
    if filas != columnas:
        raise ValueError("La matriz debe ser cuadrada.")

    # Paso 2: Calcular el polinomio característico
    I = np.eye(filas)  # Matriz identidad
    # Los valores propios son las raíces del determinante de (A - λI) = 0
    polinomio = np.poly(matriz)  # Polinomio característico

    # Paso 3: Calcular los valores propios resolviendo el polinomio característico
    valores_propios = np.roots(polinomio)

    # Paso 4: Calcular los vectores propios
    vectores_propios = []
    for lambda_val in valores_propios:
        # Resolver (A - λI) * v = 0
        A_lambda_I = matriz - lambda_val * I
        _, _, vh = np.linalg.svd(A_lambda_I)  # Descomposición SVD para resolver sistemas homogéneos
        vector_propio = vh[-1, :]  # El vector propio asociado
        vectores_propios.append(vector_propio)

    vectores_propios = np.array(vectores_propios).T  # Transponer para mantener formato convencional

    return valores_propios, vectores_propios


# Prueba de matriz B
matriz = np.array([[3, 2],
                   [3, 4]])

valores, vectores = calcular_valores_vectores_propios(matriz)

print("Valores propios:")
print(valores)

print("Vectores propios (columnas):")
print(vectores)


Valores propios:
[6. 1.]
Vectores propios (columnas):
[[-0.5547002  -0.70710678]
 [-0.83205029  0.70710678]]


In [ ]:
import numpy as np

def calcular_valores_vectores_propios(matriz):
    # Paso 1: Verificar si la matriz es cuadrada
    filas, columnas = matriz.shape
    if filas != columnas:
        raise ValueError("La matriz debe ser cuadrada.")

    # Paso 2: Calcular el polinomio característico
    I = np.eye(filas)  # Matriz identidad
    # Los valores propios son las raíces del determinante de (A - λI) = 0
    polinomio = np.poly(matriz)  # Polinomio característico

    # Paso 3: Calcular los valores propios resolviendo el polinomio característico
    valores_propios = np.roots(polinomio)

    # Paso 4: Calcular los vectores propios
    vectores_propios = []
    for lambda_val in valores_propios:
        # Resolver (A - λI) * v = 0
        A_lambda_I = matriz - lambda_val * I
        _, _, vh = np.linalg.svd(A_lambda_I)  # Descomposición SVD para resolver sistemas homogéneos
        vector_propio = vh[-1, :]  # El vector propio asociado
        vectores_propios.append(vector_propio)

    vectores_propios = np.array(vectores_propios).T  # Transponer para mantener formato convencional

    return valores_propios, vectores_propios


# Prueba de matriz C
matriz = np.array([[2, 3],
                   [1, 4]])

valores, vectores = calcular_valores_vectores_propios(matriz)

print("Valores propios:")
print(valores)

print("Vectores propios (columnas):")
print(vectores)

Valores propios:
[5. 1.]
Vectores propios (columnas):
[[ 0.70710678 -0.9486833 ]
 [ 0.70710678  0.31622777]]


In [ ]:
import numpy as np

def calcular_valores_vectores_propios(matriz):
    # Paso 1: Verificar si la matriz es cuadrada
    filas, columnas = matriz.shape
    if filas != columnas:
        raise ValueError("La matriz debe ser cuadrada.")

    # Paso 2: Calcular el polinomio característico
    I = np.eye(filas)  # Matriz identidad
    # Los valores propios son las raíces del determinante de (A - λI) = 0
    polinomio = np.poly(matriz)  # Polinomio característico

    # Paso 3: Calcular los valores propios resolviendo el polinomio característico
    valores_propios = np.roots(polinomio)

    # Paso 4: Calcular los vectores propios
    vectores_propios = []
    for lambda_val in valores_propios:
        # Resolver (A - λI) * v = 0
        A_lambda_I = matriz - lambda_val * I
        _, _, vh = np.linalg.svd(A_lambda_I)  # Descomposición SVD para resolver sistemas homogéneos
        vector_propio = vh[-1, :]  # El vector propio asociado
        vectores_propios.append(vector_propio)

    vectores_propios = np.array(vectores_propios).T  # Transponer para mantener formato convencional

    return valores_propios, vectores_propios


# Prueba de matriz D
matriz = np.array([[1, 1, 2],
                   [2, 1, 1],
                   [1, 1, 3]])

valores, vectores = calcular_valores_vectores_propios(matriz)

print("Valores propios:")
print(valores)

print("Vectores propios (columnas):")
print(vectores)

Valores propios:
[ 4.50701864  0.77812384 -0.28514248]
Vectores propios (columnas):
[[-0.53231709  0.1297142  -0.49762292]
 [-0.49863934  0.88103974  0.86033768]
 [-0.6841033  -0.45491011 -0.11041066]]


In [ ]:
import numpy as np

def calcular_valores_vectores_propios(matriz):
    # Paso 1: Verificar si la matriz es cuadrada
    filas, columnas = matriz.shape
    if filas != columnas:
        raise ValueError("La matriz debe ser cuadrada.")

    # Paso 2: Calcular el polinomio característico
    I = np.eye(filas)  # Matriz identidad
    # Los valores propios son las raíces del determinante de (A - λI) = 0
    polinomio = np.poly(matriz)  # Polinomio característico

    # Paso 3: Calcular los valores propios resolviendo el polinomio característico
    valores_propios = np.roots(polinomio)

    # Paso 4: Calcular los vectores propios
    vectores_propios = []
    for lambda_val in valores_propios:
        # Resolver (A - λI) * v = 0
        A_lambda_I = matriz - lambda_val * I
        _, _, vh = np.linalg.svd(A_lambda_I)  # Descomposición SVD para resolver sistemas homogéneos
        vector_propio = vh[-1, :]  # El vector propio asociado
        vectores_propios.append(vector_propio)

    vectores_propios = np.array(vectores_propios).T  # Transponer para mantener formato convencional

    return valores_propios, vectores_propios


# Prueba de matriz E
matriz = np.array([[1, 1, 2],
                   [2, 1, 3],
                   [1, 1, 1]])

valores, vectores = calcular_valores_vectores_propios(matriz)

print("Valores propios:")
print(valores)

print("Vectores propios (columnas):")
print(vectores)

Valores propios:
[ 4.04891734 -0.69202147 -0.35689587]
Vectores propios (columnas):
[[-0.51769363 -0.26822309  0.85467668]
 [-0.74808896 -0.75154439 -0.21108771]
 [-0.41515805  0.6026918  -0.47430977]]


In [ ]:
import numpy as np

def calcular_valores_vectores_propios(matriz):
    # Paso 1: Verificar si la matriz es cuadrada
    filas, columnas = matriz.shape
    if filas != columnas:
        raise ValueError("La matriz debe ser cuadrada.")

    # Paso 2: Calcular el polinomio característico
    I = np.eye(filas)  # Matriz identidad
    # Los valores propios son las raíces del determinante de (A - λI) = 0
    polinomio = np.poly(matriz)  # Polinomio característico

    # Paso 3: Calcular los valores propios resolviendo el polinomio característico
    valores_propios = np.roots(polinomio)

    # Paso 4: Calcular los vectores propios
    vectores_propios = []
    for lambda_val in valores_propios:
        # Resolver (A - λI) * v = 0
        A_lambda_I = matriz - lambda_val * I
        _, _, vh = np.linalg.svd(A_lambda_I)  # Descomposición SVD para resolver sistemas homogéneos
        vector_propio = vh[-1, :]  # El vector propio asociado
        vectores_propios.append(vector_propio)

    vectores_propios = np.array(vectores_propios).T  # Transponer para mantener formato convencional

    return valores_propios, vectores_propios


# Prueba de matriz F
matriz = np.array([[2, 1, 2],
                   [1, 1, 3],
                   [1, 1, 1]])

valores, vectores = calcular_valores_vectores_propios(matriz)

print("Valores propios:")
print(valores)

print("Vectores propios (columnas):")
print(vectores)

Valores propios:
[ 4.12488542 -0.76155718  0.63667176]
Vectores propios (columnas):
[[ 0.67550236 -0.07072589 -0.72653358]
 [ 0.61159354 -0.84969749  0.66793428]
 [ 0.41188579  0.52250553  0.16128473]]


In [ ]:
import numpy as np

def calcular_valores_vectores_propios(matriz):
    # Paso 1: Verificar si la matriz es cuadrada
    filas, columnas = matriz.shape
    if filas != columnas:
        raise ValueError("La matriz debe ser cuadrada.")

    # Paso 2: Calcular el polinomio característico
    I = np.eye(filas)  # Matriz identidad
    # Los valores propios son las raíces del determinante de (A - λI) = 0
    polinomio = np.poly(matriz)  # Polinomio característico

    # Paso 3: Calcular los valores propios resolviendo el polinomio característico
    valores_propios = np.roots(polinomio)

    # Paso 4: Calcular los vectores propios
    vectores_propios = []
    for lambda_val in valores_propios:
        # Resolver (A - λI) * v = 0
        A_lambda_I = matriz - lambda_val * I
        _, _, vh = np.linalg.svd(A_lambda_I)  # Descomposición SVD para resolver sistemas homogéneos
        vector_propio = vh[-1, :]  # El vector propio asociado
        vectores_propios.append(vector_propio)

    vectores_propios = np.array(vectores_propios).T  # Transponer para mantener formato convencional

    return valores_propios, vectores_propios


# Prueba de matriz G
matriz = np.array([[1, 1, 1, 2],
                   [2, 1, 1, 1],
                   [3, 2, 1, 2],
                   [2, 1, 1, 4]])

valores, vectores = calcular_valores_vectores_propios(matriz)

print("Valores propios:")
print(valores)

print("Vectores propios (columnas):")
print(vectores)

Valores propios:
[ 6.63453446  1.50856334 -0.73564154 -0.40745627]
Vectores propios (columnas):
[[ 0.38941594  0.10866639 -0.65148076 -0.38913343]
 [ 0.35142164  0.54839569  0.31969406  0.80095815]
 [ 0.55977506  0.61625428  0.68513144 -0.44482357]
 [ 0.6414904  -0.55469311  0.06295578  0.09577685]]


In [ ]:
import numpy as np

def calcular_valores_vectores_propios(matriz):
    # Paso 1: Verificar si la matriz es cuadrada
    filas, columnas = matriz.shape
    if filas != columnas:
        raise ValueError("La matriz debe ser cuadrada.")

    # Paso 2: Calcular el polinomio característico
    I = np.eye(filas)  # Matriz identidad
    # Los valores propios son las raíces del determinante de (A - λI) = 0
    polinomio = np.poly(matriz)  # Polinomio característico

    # Paso 3: Calcular los valores propios resolviendo el polinomio característico
    valores_propios = np.roots(polinomio)

    # Paso 4: Calcular los vectores propios
    vectores_propios = []
    for lambda_val in valores_propios:
        # Resolver (A - λI) * v = 0
        A_lambda_I = matriz - lambda_val * I
        _, _, vh = np.linalg.svd(A_lambda_I)  # Descomposición SVD para resolver sistemas homogéneos
        vector_propio = vh[-1, :]  # El vector propio asociado
        vectores_propios.append(vector_propio)

    vectores_propios = np.array(vectores_propios).T  # Transponer para mantener formato convencional

    return valores_propios, vectores_propios


# Prueba de matriz H
matriz = np.array([[1, 2, 1, 2],
                   [2, 1, 1, 1],
                   [3, 2, 1, 2],
                   [2, 1, 1, 4]])

valores, vectores = calcular_valores_vectores_propios(matriz)

print("Valores propios:")
print(valores)

print("Vectores propios (columnas):")
print(vectores)

Valores propios:
[ 6.82726225  1.72811591 -1.08793492 -0.46744323]
Vectores propios (columnas):
[[ 0.42853133  0.24289613 -0.71363438 -0.28400892]
 [ 0.34899468  0.4838935   0.35215497 -0.22663858]
 [ 0.55406667  0.52400705  0.598272    0.93115005]
 [ 0.62255421 -0.65746876  0.09372011 -0.03055296]]
